//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGNO
    {
        public int STT { get; set; }
        public string MAKH { get; set; }
        public System.DateTime NGAYPHATSINH { get; set; }
        public decimal NODAU { get; set; }
        public decimal PHATSINH { get; set; }
        public decimal NOCUOI { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
