//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAUSACH
    {
        public DAUSACH()
        {
            this.TONKHOes = new HashSet<TONKHO>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public int MADS { get; set; }
        public string TENSACH { get; set; }
        public string MATL { get; set; }
        public string TACGIA { get; set; }
        public int SOLUONG { get; set; }
        public decimal DONGIA { get; set; }
    
        public virtual THELOAI THELOAI { get; set; }
        public virtual ICollection<TONKHO> TONKHOes { get; set; }
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
    }
}
