//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDINH
    {
        public int NHAPTOITHIEU { get; set; }
        public int TONTRUOCNHAP { get; set; }
        public int TONSAUBAN { get; set; }
        public decimal NOTOIDA { get; set; }
        public bool THUQUANO { get; set; }
        public int STT { get; set; }
    }
}
