//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public int STT { get; set; }
        public int MADS { get; set; }
        public System.DateTime NGAYPHATSINH { get; set; }
        public int TONDAU { get; set; }
        public int PHATSINH { get; set; }
        public int TONCUOI { get; set; }
    
        public virtual DAUSACH DAUSACH { get; set; }
    }
}
