//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.PHIEUTHUNOes = new HashSet<PHIEUTHUNO>();
            this.HOADONs = new HashSet<HOADON>();
            this.CONGNOes = new HashSet<CONGNO>();
        }
    
        public string MAKH { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public bool NO { get; set; }
    
        public virtual ICollection<PHIEUTHUNO> PHIEUTHUNOes { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<CONGNO> CONGNOes { get; set; }
    }
}
