//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public PHIEUNHAP()
        {
            this.PHIEUCHIs = new HashSet<PHIEUCHI>();
            this.CHITIETPHIEUNHAPs = new HashSet<CHITIETPHIEUNHAP>();
        }
    
        public string MAPN { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public string MANV { get; set; }
        public string MANCC { get; set; }
        public decimal TONGTIEN { get; set; }
        public decimal CONNO { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual ICollection<PHIEUCHI> PHIEUCHIs { get; set; }
        public virtual ICollection<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
    }
}
