//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUCHI
    {
        public string MAPC { get; set; }
        public string MANV { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public decimal TIENCHI { get; set; }
        public string MAPN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
