//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THELOAI
    {
        public THELOAI()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.DAUSACHes = new HashSet<DAUSACH>();
        }
    
        public string MATL { get; set; }
        public string TENTL { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual ICollection<DAUSACH> DAUSACHes { get; set; }
    }
}
